// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:path/path.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Object get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-ah29D_5O0Pw6WEW8nbplM3YtyDd0jI',
    appId: '1:773430229062:web:69620f9474d6ee53ec7247',
    messagingSenderId: '773430229062',
    projectId: 'music-94111',
    authDomain: 'music-94111.firebaseapp.com',
    storageBucket: 'music-94111.appspot.com',
    measurementId: 'G-S1G0X69KFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCveMdX8k_XInpHGOZBCoumKd8s_o5Nbnk',
    appId: '1:773430229062:android:894e640ed99ff753ec7247',
    messagingSenderId: '773430229062',
    projectId: 'music-94111',
    storageBucket: 'music-94111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSnIvLAL_PxJpBeA7goj6STVAEErMQI88',
    appId: '1:773430229062:ios:8bb868dffe39cb47ec7247',
    messagingSenderId: '773430229062',
    projectId: 'music-94111',
    storageBucket: 'music-94111.appspot.com',
    iosClientId: '773430229062-b6q6ut24l1de3lf2uvksp62l4b31aqev.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSnIvLAL_PxJpBeA7goj6STVAEErMQI88',
    appId: '1:773430229062:ios:8bb868dffe39cb47ec7247',
    messagingSenderId: '773430229062',
    projectId: 'music-94111',
    storageBucket: 'music-94111.appspot.com',
    iosClientId: '773430229062-b6q6ut24l1de3lf2uvksp62l4b31aqev.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );
}
